/**
 * Short spoken fillers, rendered ahead of time. Each is tied to a moment the
 * listener can place: their own request, a slow or failed tool, a long silence.
 * No wordless murmurs or one-word phrases: speech runtimes render them
 * unpredictably, often twice.
 */
export type FillerKind = "ackQuestion" | "ackRequest" | "slowCommand" | "slowTests" | "slowInstall" | "slowBuild" | "slowBrowser" | "slowSearch" | "slow" | "toolFailed" | "toolDone" | "still";

export type VoicePhrases = Record<FillerKind, string[]> & {
  /** Spoken live when no filler played for a thinking turn. */
  think: string[];
  compacting: string[];
  compactionWait: string;
  compactionDone: string;
  compactionStopped: string;
};

/**
 * Keyed by the voice input language. A language missing here gets no fillers,
 * with status notices in English, rather than guessed wording.
 */
export const PHRASES: Record<string, VoicePhrases> = {
  en: {
    ackQuestion: ["Let me see.", "Let me check."],
    ackRequest: ["Okay, on it.", "Sure thing.", "Got it."],
    slowCommand: ["The command is still running."],
    slowTests: ["The tests are still running."],
    slowInstall: ["Still installing."],
    slowBuild: ["The build is still running."],
    slowBrowser: ["The page is still loading."],
    slowSearch: ["Still searching."],
    slow: ["This is taking a moment.", "Still working on it."],
    toolFailed: ["That didn't work.", "That failed, let me check."],
    toolDone: ["Okay, let's see.", "Right, let's take a look."],
    still: ["Still on it.", "Bear with me."],
    think: ["Let me think about that for a moment.", "Give me a moment to think this through.", "Let me consider that.", "I’m thinking through your request.", "Let me take a moment with that."],
    compacting: ["My context is getting full. Let me quickly compact our conversation before I continue.", "I need a little room in my context. Let me summarize our conversation, then I'll carry on.", "Let me do a quick context compaction so I can keep going."],
    compactionWait: "I'm still compacting our conversation. Please wait a moment; I'll let you know when I'm ready.",
    compactionDone: "Context compaction is done. I'm ready to continue.",
    compactionStopped: "Context compaction stopped before it finished.",
  },
  de: {
    ackQuestion: ["Mal sehen.", "Moment, ich schau mal."],
    ackRequest: ["Alles klar.", "Mach ich.", "Okay, verstanden."],
    slowCommand: ["Der Befehl läuft noch."],
    slowTests: ["Die Tests laufen noch."],
    slowInstall: ["Die Installation läuft noch."],
    slowBuild: ["Der Build läuft noch."],
    slowBrowser: ["Die Seite lädt noch."],
    slowSearch: ["Die Suche läuft noch."],
    slow: ["Das dauert noch einen Moment.", "Einen Moment noch."],
    toolFailed: ["Das hat nicht geklappt.", "Das ging schief, ich schau mal."],
    toolDone: ["Okay, mal sehen.", "So, schauen wir mal."],
    still: ["Bin noch dran.", "Dauert noch ein bisschen."],
    think: ["Moment, ich denke kurz nach.", "Lass mich das kurz durchdenken.", "Gute Frage, einen Moment."],
    compacting: ["Mein Kontext wird voll. Ich fasse unser Gespräch kurz zusammen und mache dann weiter.", "Ich brauche etwas Platz im Kontext. Einen Moment, ich fasse kurz zusammen."],
    compactionWait: "Ich fasse unser Gespräch noch zusammen. Einen Moment bitte, ich sage Bescheid, wenn ich so weit bin.",
    compactionDone: "Die Zusammenfassung ist fertig. Ich kann weitermachen.",
    compactionStopped: "Die Zusammenfassung wurde abgebrochen, bevor sie fertig war.",
  },
  es: {
    ackQuestion: ["A ver.", "Déjame ver."],
    ackRequest: ["Vale, entendido.", "De acuerdo.", "Ahora mismo."],
    slowCommand: ["El comando sigue en marcha."],
    slowTests: ["Las pruebas siguen ejecutándose."],
    slowInstall: ["La instalación sigue en curso."],
    slowBuild: ["La compilación sigue en marcha."],
    slowBrowser: ["La página sigue cargando."],
    slowSearch: ["Sigo buscando."],
    slow: ["Esto tarda un momento.", "Un momento más."],
    toolFailed: ["Eso no ha funcionado.", "Algo falló, lo reviso."],
    toolDone: ["Bien, a ver.", "Vale, veamos."],
    still: ["Sigo en ello.", "Un poco más."],
    think: ["Déjame pensarlo un momento.", "Un momento, lo estoy pensando.", "Déjame considerarlo."],
    compacting: ["Mi contexto se está llenando. Voy a resumir nuestra conversación y sigo.", "Necesito un poco de espacio en el contexto. Un momento, resumo rápido."],
    compactionWait: "Todavía estoy resumiendo la conversación. Espera un momento; te aviso cuando esté listo.",
    compactionDone: "El resumen está listo. Puedo continuar.",
    compactionStopped: "El resumen se detuvo antes de terminar.",
  },
  fr: {
    ackQuestion: ["Voyons voir.", "Je regarde."],
    ackRequest: ["D’accord, c’est parti.", "C’est noté.", "Je m’en occupe."],
    slowCommand: ["La commande tourne encore."],
    slowTests: ["Les tests tournent encore."],
    slowInstall: ["L’installation est encore en cours."],
    slowBuild: ["La compilation est encore en cours."],
    slowBrowser: ["La page charge encore."],
    slowSearch: ["La recherche continue."],
    slow: ["Ça prend un instant.", "Encore un instant."],
    toolFailed: ["Ça n’a pas marché.", "Ça a échoué, je regarde."],
    toolDone: ["Bon, voyons.", "D’accord, regardons."],
    still: ["J’y suis encore.", "Encore un peu."],
    think: ["Laisse-moi réfléchir un instant.", "Un instant, je réfléchis.", "Voyons voir."],
    compacting: ["Mon contexte se remplit. Je résume notre conversation, puis je continue.", "J’ai besoin d’un peu de place dans mon contexte. Un instant, je résume."],
    compactionWait: "Je suis encore en train de résumer notre conversation. Un instant, je te préviens dès que c’est prêt.",
    compactionDone: "Le résumé est terminé. Je peux continuer.",
    compactionStopped: "Le résumé s’est arrêté avant la fin.",
  },
  it: {
    ackQuestion: ["Vediamo un po’.", "Controllo subito."],
    ackRequest: ["Va bene.", "D’accordo.", "Ci penso io."],
    slowCommand: ["Il comando è ancora in esecuzione."],
    slowTests: ["I test sono ancora in corso."],
    slowInstall: ["L’installazione è ancora in corso."],
    slowBuild: ["La build è ancora in corso."],
    slowBrowser: ["La pagina si sta ancora caricando."],
    slowSearch: ["La ricerca è ancora in corso."],
    slow: ["Ci vuole un momento.", "Ancora un attimo."],
    toolFailed: ["Non ha funzionato.", "Qualcosa è andato storto, controllo."],
    toolDone: ["Bene, vediamo.", "Ok, diamo un’occhiata."],
    still: ["Ci sto ancora lavorando.", "Ancora un po’."],
    think: ["Fammi pensare un attimo.", "Un momento, ci sto pensando.", "Vediamo."],
    compacting: ["Il mio contesto si sta riempiendo. Riassumo la conversazione e poi continuo.", "Mi serve un po’ di spazio nel contesto. Un attimo, faccio un riassunto."],
    compactionWait: "Sto ancora riassumendo la conversazione. Aspetta un momento, ti avviso quando ho finito.",
    compactionDone: "Il riassunto è pronto. Posso continuare.",
    compactionStopped: "Il riassunto si è interrotto prima di finire.",
  },
  pt: {
    ackQuestion: ["Deixa eu ver.", "Vou verificar."],
    ackRequest: ["Tá bom.", "Beleza, deixa comigo.", "Pode deixar."],
    slowCommand: ["O comando ainda está rodando."],
    slowTests: ["Os testes ainda estão rodando."],
    slowInstall: ["A instalação ainda está em andamento."],
    slowBuild: ["O build ainda está rodando."],
    slowBrowser: ["A página ainda está carregando."],
    slowSearch: ["A busca ainda está rodando."],
    slow: ["Isso está levando um momento.", "Só mais um momento."],
    toolFailed: ["Isso não funcionou.", "Deu erro, vou verificar."],
    toolDone: ["Certo, vamos ver.", "Beleza, vamos dar uma olhada."],
    still: ["Ainda estou nisso.", "Só mais um pouco."],
    think: ["Deixa eu pensar um momento.", "Um momento, estou pensando.", "Deixa eu ver."],
    compacting: ["Meu contexto está ficando cheio. Vou resumir a conversa e depois continuo.", "Preciso de espaço no contexto. Um momento, vou resumir."],
    compactionWait: "Ainda estou resumindo a conversa. Espera um momento; aviso quando estiver tudo pronto.",
    compactionDone: "O resumo está pronto. Posso continuar.",
    compactionStopped: "O resumo parou antes de terminar.",
  },
  ru: {
    ackQuestion: ["Сейчас посмотрим.", "Секунду, проверю."],
    ackRequest: ["Хорошо, сейчас.", "Понятно, делаю.", "Сейчас сделаю."],
    slowCommand: ["Команда ещё выполняется."],
    slowTests: ["Тесты ещё идут."],
    slowInstall: ["Установка ещё идёт."],
    slowBuild: ["Сборка ещё идёт."],
    slowBrowser: ["Страница ещё загружается."],
    slowSearch: ["Поиск ещё идёт."],
    slow: ["Это займёт ещё немного времени.", "Ещё секунду."],
    toolFailed: ["Не получилось.", "Что-то пошло не так, проверю."],
    toolDone: ["Так, посмотрим.", "Хорошо, давай посмотрим."],
    still: ["Ещё работаю.", "Ещё немного."],
    think: ["Дай мне немного подумать.", "Секунду, я подумаю.", "Сейчас посмотрим."],
    compacting: ["Мой контекст заполняется. Кратко подытожу разговор и продолжу.", "Мне нужно место в контексте. Секунду, подытожу."],
    compactionWait: "Я ещё подытоживаю разговор. Подожди немного, я скажу, когда всё будет готово.",
    compactionDone: "Сжатие контекста завершено. Могу продолжать.",
    compactionStopped: "Сжатие контекста остановилось, не завершившись.",
  },
  zh: {
    ackQuestion: ["我看看。", "我查一下。"],
    ackRequest: ["好的。", "没问题。", "我来处理。"],
    slowCommand: ["命令还在运行。"],
    slowTests: ["测试还在运行。"],
    slowInstall: ["还在安装。"],
    slowBuild: ["还在构建。"],
    slowBrowser: ["页面还在加载。"],
    slowSearch: ["还在搜索。"],
    slow: ["还需要一点时间。", "再等一下。"],
    toolFailed: ["没成功。", "出错了，我看一下。"],
    toolDone: ["好，我们来看看。", "好，看看结果。"],
    still: ["还在处理。", "再稍等一下。"],
    think: ["让我想一想。", "稍等，我考虑一下。", "我想想看。"],
    compacting: ["我的上下文快满了。我先简单总结一下我们的对话，然后继续。", "我需要一些上下文空间。稍等，我总结一下。"],
    compactionWait: "我还在总结我们的对话。请稍等，准备好了我会告诉你。",
    compactionDone: "上下文压缩完成了，我可以继续了。",
    compactionStopped: "上下文压缩在完成前停止了。",
  },
  ja: {
    ackQuestion: ["見てみますね。", "確認しますね。"],
    ackRequest: ["わかりました。", "了解です。", "やってみます。"],
    slowCommand: ["コマンドはまだ実行中です。"],
    slowTests: ["テストはまだ実行中です。"],
    slowInstall: ["まだインストール中です。"],
    slowBuild: ["まだビルド中です。"],
    slowBrowser: ["ページはまだ読み込み中です。"],
    slowSearch: ["まだ検索中です。"],
    slow: ["もう少しかかります。", "もう少々お待ちください。"],
    toolFailed: ["うまくいきませんでした。", "エラーが出ました。確認します。"],
    toolDone: ["では、見てみましょう。", "さて、確認します。"],
    still: ["まだ作業中です。", "もう少しです。"],
    think: ["少し考えさせてください。", "ちょっと考えますね。", "えーと、考えてみます。"],
    compacting: ["コンテキストがいっぱいになってきました。会話を要約してから続けます。", "コンテキストに少し余裕が必要です。少々お待ちください、要約します。"],
    compactionWait: "まだ会話を要約しています。少々お待ちください。終わったらお知らせします。",
    compactionDone: "要約が終わりました。続けられます。",
    compactionStopped: "要約は完了する前に止まりました。",
  },
  ko: {
    ackQuestion: ["어디 볼게요.", "확인해 볼게요."],
    ackRequest: ["네, 알겠어요.", "좋아요.", "바로 할게요."],
    slowCommand: ["명령이 아직 실행 중이에요."],
    slowTests: ["테스트가 아직 실행 중이에요."],
    slowInstall: ["아직 설치 중이에요."],
    slowBuild: ["아직 빌드 중이에요."],
    slowBrowser: ["페이지가 아직 로딩 중이에요."],
    slowSearch: ["아직 검색 중이에요."],
    slow: ["조금 더 걸려요.", "잠시만 더요."],
    toolFailed: ["잘 안 됐어요.", "오류가 났네요, 확인해 볼게요."],
    toolDone: ["자, 한번 볼게요.", "좋아요, 결과를 볼게요."],
    still: ["아직 작업 중이에요.", "조금만 더요."],
    think: ["잠깐 생각해 볼게요.", "잠시만요, 생각 중이에요.", "어디 보자."],
    compacting: ["컨텍스트가 차고 있어요. 대화를 간단히 요약하고 계속할게요.", "컨텍스트 공간이 좀 필요해요. 잠시만요, 요약할게요."],
    compactionWait: "아직 대화를 요약하고 있어요. 잠시만 기다려 주세요. 준비되면 알려 드릴게요.",
    compactionDone: "요약이 끝났어요. 계속할 수 있어요.",
    compactionStopped: "요약이 끝나기 전에 중단됐어요.",
  },
  hi: {
    ackQuestion: ["देखते हैं।", "एक पल, देखते हैं।"],
    ackRequest: ["ठीक है।", "जी, समझ गए।", "अभी करते हैं।"],
    slowCommand: ["कमांड अभी चल रही है।"],
    slowTests: ["टेस्ट अभी चल रहे हैं।"],
    slowInstall: ["इंस्टॉलेशन अभी चल रहा है।"],
    slowBuild: ["बिल्ड अभी चल रहा है।"],
    slowBrowser: ["पेज अभी लोड हो रहा है।"],
    slowSearch: ["खोज अभी जारी है।"],
    slow: ["इसमें थोड़ा समय लग रहा है।", "बस एक पल और।"],
    toolFailed: ["यह नहीं हुआ।", "कुछ गड़बड़ हुई, देखते हैं।"],
    toolDone: ["ठीक है, देखते हैं।", "चलिए, नतीजा देखते हैं।"],
    still: ["काम जारी है।", "बस थोड़ा और।"],
    think: ["एक पल, सोचने दीजिए।", "इस पर थोड़ा सोचने दीजिए।", "देखते हैं।"],
    compacting: ["कॉन्टेक्स्ट भर रहा है। बातचीत का सारांश बनाकर आगे बढ़ते हैं।", "कॉन्टेक्स्ट में थोड़ी जगह चाहिए। एक पल, सारांश बन रहा है।"],
    compactionWait: "बातचीत का सारांश अभी बन रहा है। कृपया थोड़ा रुकिए, तैयार होते ही बताया जाएगा।",
    compactionDone: "सारांश पूरा हो गया। अब आगे बढ़ सकते हैं।",
    compactionStopped: "सारांश पूरा होने से पहले रुक गया।",
  },
  ar: {
    ackQuestion: ["لنرَ.", "دعني أتحقق."],
    ackRequest: ["حسنًا، سأبدأ.", "تمام، فهمت.", "سأبدأ الآن."],
    slowCommand: ["الأمر لا يزال قيد التشغيل."],
    slowTests: ["الاختبارات لا تزال قيد التشغيل."],
    slowInstall: ["التثبيت لا يزال جاريًا."],
    slowBuild: ["البناء لا يزال جاريًا."],
    slowBrowser: ["الصفحة لا تزال قيد التحميل."],
    slowSearch: ["البحث لا يزال جاريًا."],
    slow: ["سيستغرق هذا لحظة.", "لحظة أخرى."],
    toolFailed: ["لم ينجح ذلك.", "حدث خطأ، سأتحقق."],
    toolDone: ["حسنًا، لنرَ.", "تمام، لنلقِ نظرة."],
    still: ["ما زلت أعمل على ذلك.", "قليلًا بعد."],
    think: ["دعني أفكر في ذلك لحظة.", "لحظة، أفكر في الأمر.", "لنرَ."],
    compacting: ["سياقي يمتلئ. سألخّص محادثتنا بسرعة ثم أتابع.", "أحتاج إلى بعض المساحة في السياق. لحظة، سألخّص."],
    compactionWait: "ما زلت ألخّص محادثتنا. انتظر لحظة من فضلك، وسأخبرك عندما يصبح كل شيء جاهزًا.",
    compactionDone: "انتهى التلخيص. يمكنني المتابعة.",
    compactionStopped: "توقف التلخيص قبل أن يكتمل.",
  },
};

/** The configured input language, or the first requested one with phrases when voice auto-detects. */
export function phraseLanguage(configured: string | undefined, requested: readonly string[] = []) {
  if (configured && configured !== "auto") return configured;
  return requested.map(tag => tag.toLowerCase().split("-")[0]).find(code => code in PHRASES) ?? "en";
}

/** Status notices fall back to English; fillers do not, so they never speak the wrong language. */
export const statusPhrases = (language: string) => PHRASES[language] ?? PHRASES.en;

const FILLER_KINDS: FillerKind[] = ["ackRequest", "ackQuestion", "slow", "toolFailed", "toolDone", "still", "slowCommand", "slowTests", "slowBrowser", "slowSearch", "slowInstall", "slowBuild"];
/** One phrase of every kind first, then the variations, so the most useful clips are ready soonest. */
export function fillerPhrases(language: string): { kind: FillerKind; text: string }[] {
  const table = PHRASES[language];
  if (!table) return [];
  const rounds = Math.max(...FILLER_KINDS.map(kind => table[kind].length));
  return Array.from({ length: rounds }, (_, i) => FILLER_KINDS.filter(kind => i < table[kind].length).map(kind => ({ kind, text: table[kind][i] }))).flat();
}
